POST http://localhost/jurusan/ 
Content-Type: "application/json"
Authorization: iniadalahtoken

{
    "Jurusan": "Informatika",
    "Fakultas": "Sekolah Teknik Elektro dan Informatika",
    "Fakultas_short": "STEI",
    "jurusan_SHORT": "IF"
}
###
POST http://localhost/jurusan/ 
Content-Type: "application/json"
Authorization: iniadalahtoken

{
    "Jurusan": "Sistem Teknologi Informasi",
    "Fakultas": "Sekolah Teknik Elektro dan Informatika",
    "Fakultas_short": "STEI",
    "jurusan_SHORT": "STI"
}
###
POST http://localhost/jurusan/ 
Content-Type: "application/json"
Authorization: iniadalahtoken

{
    "Jurusan": "Teknik Lingkungan",
    "Fakultas": "Fakultas Teknik Sipil dan Lingkungan",
    "Fakultas_short": "FTSL",
    "jurusan_SHORT": "TL"
}
###

GET http://localhost/jurusan/507a7bba-c96f-4d89-86a1-18f03695b402
	
###
DELETE http://localhost/jurusan/e2c8d5d7-03eb-4dfa-af57-cb7b9b73704c

###
PUT http://localhost/jurusan/
Content-Type: "application/json"
Authorization: iniadalahtoken

{
    "id_jurusan": "67a29f9b-a456-40bd-b433-ee6dc2981014",
    "fakultas_short": "TL",
    "jurusan": "Teknik Lingkungan"
}