# type CreateMessageSerializer struct {
# 	IdWisudawan string `json:"id_wisudawan" wispril:"required"`
# 	Message     string `json:"message" wispril:"required"`
# 	Sender      string `json:"sender" wispril:"required" binding:"lte=255"`
# }
POST http://localhost/message/
Content-Type: application/json

{
    "id_wisudawan" : "656cd8af-2838-45b5-b9e2-78a73a6427e7",
    "message" : "Message1113",
    "sender" : "Anonymous11113"
}

###
GET http://localhost/message/wisudawan/eecacc01-6748-46f7-8d48-642d2e8fe584

###
DELETE http://localhost/message/400aee33-24d8-4f79-820d-60aab85f7ab3
Authorization: iniadalahtoken
