POST http://localhost/wisudawan/ 
Content-Type: "application/json"
Authorization: iniadalahtoken

{
    "nim": 13519000,
    "nama": "Ssk",
    "nama_panggilan": "Saaapapun",
    "judul_ta": "Howsss.?",
    "angkatan": 2,
    "id_jurusan": "1f6e7ec1-d84d-4c48-917b-2a1a60445c78",
    "instagram": "c",
    "linkedin": "b",
    "twitter": "a",
    "tempat_lahir": "11111",
    "tanggal_lahir": "12-02-2001",
    "photo": "123aa"
}
###

DELETE http://localhost/wisudawan/318839c4-11eb-4d45-8204-5f25b91ac55c
Authorization: iniadalahtoken

###
GET http://localhost/wisudawan/id/eeb917bb-95b5-408f-a73f-bd52caa0a7f1
###
PUT http://localhost/wisudawan/
Authorization: iniadalahtoken

{
    "nim" : 13519001,
    "tanggal_lahir": "12-02-2011"
}
###
GET http://localhost/wisudawan/org/HMIF
###