POST http://localhost/wisudawan/ 
Content-Type: "application/json"
Authorization: iniadalahtoken

{
    "nim": 13519000,
    "nama": "Ssk",
    "nama_panggilan": "Saaapapun",
    "judul_ta": "Howsss.?",
    "angkatan": 2,
    "id_jurusan": "1c8b18f7-0a10-428d-ae0a-90806ec01451",
    "instagram": "c",
    "linkedin": "b",
    "twitter": "a",
    "tempat_lahir": "11111",
    "tanggal_lahir": "1234",
    "photo": "123aa"
}
###

DELETE http://localhost/wisudawan/318839c4-11eb-4d45-8204-5f25b91ac55c
Authorization: iniadalahtoken

###
GET http://localhost/wisudawan/b6e8966f-5fe9-4c4a-90d3-c642a403a363
###
PUT http://localhost/wisudawan/
Authorization: iniadalahtoken

{
    "id_wisudawan" : "2cad3ea7-69c3-453d-b316-0c1c3d675b5a",
    "nim": 13519222,
    "nama": "Siapa kek",
    "nama_panggilan": "Siapapun",
    "judul_ta": "Saya belum Ta",
    "angkatan": 15,
    "id_jurusan": "1c8b18f7-0a10-428d-ae0a-90806ec01451",
    "instagram": "",
    "linkedin": "",
    "twitter": "",
    "tempat_lahir": "",
    "tanggal_lahir": "",
    "photo": ""
}