POST http://localhost:80/jurusan/ 
Content-Type: "application/json"

{
    "JuRusan": "ziizza",
    "Fakultas": "gagas",
    "Fakultas_short": "1aa",
    "jUrUsAn_sHort": "sds"
}
###
GET http://localhost:80/jurusan/1dde1bf8-ac86-44a6-97c2-0cd4393c44fb
	
###
DELETE http://localhost:80/jurusan/e2c8d5d7-03eb-4dfa-af57-cb7b9b73704c

###
PUT http://localhost:80/jurusan/ 
Content-Type: "application/json"

{
    "id_jurusan": "1dde1bf8-ac86-44a6-97c2-0cd4393c44fb",
    "fakultas_short": "nyam",
    "jurusan": "123"
}